### ISSUE TITLE
Website is completely broken (Dashboard, download, etc)

### ISSUE THREAD

**Issue by paz** [weeryan17/Wee-Utilities#8]
What plugin are you having an issue with:

Discord Groups. (REWRITE BETA)

What is the issue:

On the main website dashboard shows an SQL authentication error and on both websites the download doesn't exist whatsoever.

If you have an error put it and pastbin and put the link here:

How can I reproduce this:
just go to the website lmao

**Comment by weeryan17** [comment]
Sorry about that I forgot to renew the mysql database. we're switching everything over to local mysql server atm but that will take time. Sorry about this inconvenience.

**Comment by RihanArfan** [comment]
The website is back and most things should be running fine.
If you face any other issues, feel free to reply and report them.
